language: node_js

node_js:
  - "8"
  - "7"
  - "6"

scripts:
  - npm run test
  - npm run build

notifications:
  email:
    - mama.whowho@gmail.com

after_success: 'npm run coveralls'

cache:
  directories:
    - "node_modules"

env:
  global:
    - CI=true
